[workspace]
members = [
    "contracts/factory",
    "contracts/vault",
    "contracts/share_token",
    "contracts/oracle",
    "contracts/strategies/blend",
    "contracts/strategies/soroswap_lp",
    "contracts/strategies/phoenix_lp",
    "contracts/trade_guards/soroswap",
    "contracts/trade_guards/phoenix",
    "contracts/integration_tests",
    "contracts/mock_blend_pool",
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = { version = "27.0.0", features = [] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
