[workspace]
members = [
    "contracts/asset_handler",
    "contracts/factory",
    "contracts/vault",
    "contracts/share_token",
    "contracts/oracle",
    "contracts/oracle_adapters/reflector",
    "contracts/oracle_adapters/dia",
    "contracts/strategies/blend",
    "contracts/strategies/soroswap_lp",
    "contracts/strategies/phoenix_lp",
"contracts/integration_tests",
    "contracts/mock_blend_pool",
    "contracts/mock_asset",
    "contracts/mock_soroswap_router",
    "contracts/mock_phoenix_pool",
]
resolver = "2"

[workspace.dependencies]
soroban-sdk = { version = "22.0.1", features = [] }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
