[package]
name = "factory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { workspace = true }
asset_handler = { path = "../asset_handler" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
asset_handler = { path = "../asset_handler", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils", "asset_handler/testutils"]
