//! SoroswapLpStrategy storage layout.
//!
//! All state is kept in **instance storage** so its TTL is tied to the contract
//! instance itself.  This is appropriate because the strategy's liveness is
//! coupled to the vault's liveness.
//!
//! | Key          | Type      | Description                                        |
//! |--------------|-----------|----------------------------------------------------|
//! | `Vault`      | `Address` | Owning vault contract                              |
//! | `AssetA`     | `Address` | First token in the Soroswap pair                   |
//! | `AssetB`     | `Address` | Second token in the Soroswap pair                  |
//! | `LpToken`    | `Address` | Soroswap pair / LP token contract                  |
//! | `Router`     | `Address` | Soroswap router contract                           |
//! | `Manager`    | `Address` | Account allowed to pause / unpause and set oracle  |
//! | `Name`       | `String`  | Human-readable strategy name                       |
//! | `Paused`     | `bool`    | Emergency pause flag                               |
//! | `LpBalance`  | `i128`    | Running total of LP tokens held by this strategy   |
//! | `Oracle`     | `Address` | Optional oracle for reserve-decomposition NAV      |

use crate::error::SoroswapLpError;
use soroban_sdk::{contracttype, panic_with_error, Address, Env, String};

// ---------------------------------------------------------------------------
// TTL constants (ledgers; ~6 s/ledger on Stellar mainnet)
// ---------------------------------------------------------------------------

/// Ledgers added to the instance TTL on every entry-point call.
/// 34 560 ledgers ≈ 2.4 days.
pub const INSTANCE_BUMP_AMOUNT: u32 = 34_560;

/// Trigger a bump when the remaining instance TTL drops below this threshold.
/// 17 280 ledgers ≈ 1.2 days.
pub const INSTANCE_LIFETIME_THRESHOLD: u32 = 17_280;

// ---------------------------------------------------------------------------
// Storage key enum
// ---------------------------------------------------------------------------

/// All keys stored in instance storage by the SoroswapLpStrategy.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DataKey {
    /// Address of the vault that owns this strategy deployment.
    Vault,
    /// First token in the Soroswap liquidity pair (e.g. USDC).
    AssetA,
    /// Second token in the Soroswap liquidity pair (e.g. XLM).
    AssetB,
    /// Soroswap pair / LP token contract address.  In Soroswap the pair
    /// contract is also the LP token contract — they share the same address.
    LpToken,
    /// Soroswap router contract used to add and remove liquidity.
    Router,
    /// Manager account allowed to pause / unpause and configure the oracle.
    Manager,
    /// Human-readable name for this strategy instance (e.g. "Soroswap USDC/XLM LP").
    Name,
    /// Emergency pause flag.  When `true`, `deposit_liquidity` and `withdraw`
    /// revert immediately.
    Paused,
    /// Cumulative LP tokens held by this strategy contract.
    /// Incremented on `deposit_liquidity` and decremented on `withdraw`.
    LpBalance,
    /// Optional oracle contract for reserve-decomposition NAV (dHedge V2 §3).
    ///
    /// When set, `get_value()` prices the LP position as:
    /// ```text
    /// share        = lp_balance / pair.total_supply()
    /// pool_value   = pair.get_reserves().0 × oracle.get_price(asset_a) / PRICE_PRECISION
    ///              + pair.get_reserves().1 × oracle.get_price(asset_b) / PRICE_PRECISION
    /// get_value()  = pool_value × share
    /// ```
    /// This correctly accounts for impermanent loss without requiring an LP
    /// token oracle — only the underlying asset prices are needed.
    Oracle,
}

// ---------------------------------------------------------------------------
// Internal TTL helper
// ---------------------------------------------------------------------------

fn bump(env: &Env) {
    env.storage()
        .instance()
        .extend_ttl(INSTANCE_LIFETIME_THRESHOLD, INSTANCE_BUMP_AMOUNT);
}

// ---------------------------------------------------------------------------
// Initialization guard
// ---------------------------------------------------------------------------

/// Return `true` when the strategy has been initialized.
pub fn is_initialized(env: &Env) -> bool {
    env.storage().instance().has(&DataKey::Vault)
}

// ---------------------------------------------------------------------------
// Storage accessors — generated by macro
// ---------------------------------------------------------------------------

macro_rules! simple_set {
    ($fn_name:ident, $key:ident, $t:ty) => {
        /// Persist the value in instance storage and extend the TTL.
        pub fn $fn_name(env: &Env, val: &$t) {
            bump(env);
            env.storage().instance().set(&DataKey::$key, val);
        }
    };
}

macro_rules! simple_get {
    ($fn_name:ident, $key:ident, $t:ty) => {
        /// Read the value from instance storage.
        ///
        /// # Panics
        /// Panics with [`SoroswapLpError::NotInitialized`] if the key is absent.
        pub fn $fn_name(env: &Env) -> $t {
            bump(env);
            env.storage()
                .instance()
                .get(&DataKey::$key)
                .unwrap_or_else(|| panic_with_error!(env, SoroswapLpError::NotInitialized))
        }
    };
}

simple_set!(set_vault, Vault, Address);
simple_get!(get_vault, Vault, Address);
simple_set!(set_asset_a, AssetA, Address);
simple_get!(get_asset_a, AssetA, Address);
simple_set!(set_asset_b, AssetB, Address);
simple_get!(get_asset_b, AssetB, Address);
simple_set!(set_lp_token, LpToken, Address);
simple_get!(get_lp_token, LpToken, Address);
simple_set!(set_router, Router, Address);
simple_get!(get_router, Router, Address);
simple_set!(set_manager, Manager, Address);
simple_get!(get_manager, Manager, Address);
simple_set!(set_name, Name, String);
simple_get!(get_name, Name, String);

// ---------------------------------------------------------------------------
// Pause flag
// ---------------------------------------------------------------------------

/// Persist the pause flag.
pub fn set_paused(env: &Env, v: bool) {
    bump(env);
    env.storage().instance().set(&DataKey::Paused, &v);
}

/// Read the pause flag (defaults to `false` when not yet set).
pub fn get_paused(env: &Env) -> bool {
    bump(env);
    env.storage()
        .instance()
        .get(&DataKey::Paused)
        .unwrap_or(false)
}

// ---------------------------------------------------------------------------
// LP balance
// ---------------------------------------------------------------------------

/// Persist the cumulative LP token balance.
pub fn set_lp_balance(env: &Env, v: i128) {
    bump(env);
    env.storage().instance().set(&DataKey::LpBalance, &v);
}

/// Read the cumulative LP token balance (defaults to `0` before any deposits).
pub fn get_lp_balance(env: &Env) -> i128 {
    bump(env);
    env.storage()
        .instance()
        .get(&DataKey::LpBalance)
        .unwrap_or(0)
}

// ---------------------------------------------------------------------------
// Oracle (reserve-decomposition NAV)
// ---------------------------------------------------------------------------

/// Persist the oracle address used for reserve-decomposition NAV.
pub fn set_oracle(env: &Env, v: &Address) {
    bump(env);
    env.storage().instance().set(&DataKey::Oracle, v);
}

/// Return the oracle address, or `None` if not configured.
///
/// When `None`, `get_value()` returns the raw LP token balance as a fallback.
pub fn get_oracle(env: &Env) -> Option<Address> {
    bump(env);
    env.storage().instance().get(&DataKey::Oracle)
}
