//! PhoenixLpStrategy storage layout.
//!
//! All state is kept in **instance storage** so its TTL is tied to the contract
//! instance itself.
//!
//! | Key            | Type      | Description                                      |
//! |----------------|-----------|--------------------------------------------------|
//! | `Vault`        | `Address` | Owning vault contract                            |
//! | `AssetA`       | `Address` | First token in the Phoenix pair                  |
//! | `AssetB`       | `Address` | Second token in the Phoenix pair                 |
//! | `ShareToken`   | `Address` | Phoenix LP share token (auto-queried from pool)  |
//! | `PhoenixPool`  | `Address` | Phoenix pool contract                            |
//! | `Manager`      | `Address` | Account allowed to pause / unpause               |
//! | `Name`         | `String`  | Human-readable strategy name                     |
//! | `Paused`       | `bool`    | Emergency pause flag                             |
//! | `TotalShares`  | `i128`    | Running total of Phoenix share tokens held       |
//! | `Oracle`       | `Address` | Optional oracle used for reserve decomposition   |

use crate::error::PhoenixLpError;
use soroban_sdk::{contracttype, panic_with_error, Address, Env, String};

// ---------------------------------------------------------------------------
// TTL constants (ledgers; ~6 s/ledger on Stellar mainnet)
// ---------------------------------------------------------------------------

/// Ledgers added to the instance TTL on every entry-point call.
/// 34 560 ledgers ≈ 2.4 days.
pub const INSTANCE_BUMP_AMOUNT: u32 = 34_560;

/// Trigger a bump when the remaining instance TTL drops below this threshold.
/// 17 280 ledgers ≈ 1.2 days.
pub const INSTANCE_LIFETIME_THRESHOLD: u32 = 17_280;

// ---------------------------------------------------------------------------
// Storage key enum
// ---------------------------------------------------------------------------

/// All keys stored in instance storage by the PhoenixLpStrategy.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DataKey {
    /// Address of the vault that owns this strategy deployment.
    Vault,
    /// First token in the Phoenix liquidity pair (e.g. USDC).
    AssetA,
    /// Second token in the Phoenix liquidity pair (e.g. XLM).
    AssetB,
    /// Phoenix LP share token contract address.
    /// Automatically queried from the pool during `initialize` via
    /// `phoenix_pool.query_share_token_address()`.
    ShareToken,
    /// Phoenix pool contract used for `provide_liquidity` / `withdraw_liquidity`.
    PhoenixPool,
    /// Manager address captured at initialization only.
    ///
    /// This address is stored solely to satisfy the `manager.require_auth()`
    /// call during `initialize` (front-running prevention).  It is **not**
    /// consulted by post-initialization admin operations (`pause`, `unpause`,
    /// `set_oracle`), which instead derive authority from `vault.get_manager()`
    /// on-chain at call time.
    Manager,
    /// Human-readable name for this strategy instance.
    Name,
    /// Emergency pause flag.  When `true`, `deposit_liquidity` and `withdraw`
    /// revert immediately.
    Paused,
    /// Cumulative Phoenix share tokens held by this strategy contract.
    /// Incremented on `deposit_liquidity`, decremented on `withdraw`.
    TotalShares,

    /// Optional oracle contract used to price underlying assets for NAV.
    Oracle,
}

// ---------------------------------------------------------------------------
// Internal TTL helper
// ---------------------------------------------------------------------------

fn bump(env: &Env) {
    env.storage()
        .instance()
        .extend_ttl(INSTANCE_LIFETIME_THRESHOLD, INSTANCE_BUMP_AMOUNT);
}

// ---------------------------------------------------------------------------
// Initialization guard
// ---------------------------------------------------------------------------

/// Return `true` when the strategy has been initialized.
pub fn is_initialized(env: &Env) -> bool {
    env.storage().instance().has(&DataKey::Vault)
}

// ---------------------------------------------------------------------------
// Address accessors — generated by macro
// ---------------------------------------------------------------------------

macro_rules! addr_set {
    ($fn:ident, $k:ident) => {
        /// Persist the address in instance storage and extend the TTL.
        pub fn $fn(env: &Env, v: &Address) {
            bump(env);
            env.storage().instance().set(&DataKey::$k, v);
        }
    };
}
macro_rules! addr_get {
    ($fn:ident, $k:ident) => {
        /// Read the address from instance storage.
        ///
        /// # Panics
        /// Panics with [`PhoenixLpError::NotInitialized`] if the key is absent.
        pub fn $fn(env: &Env) -> Address {
            bump(env);
            env.storage()
                .instance()
                .get(&DataKey::$k)
                .unwrap_or_else(|| panic_with_error!(env, PhoenixLpError::NotInitialized))
        }
    };
}

// Optional address helpers (for Oracle)
pub fn set_oracle(env: &Env, v: &Address) {
    bump(env);
    env.storage().instance().set(&DataKey::Oracle, v);
}

pub fn get_oracle(env: &Env) -> Option<Address> {
    bump(env);
    env.storage().instance().get(&DataKey::Oracle)
}

// ---------------------------------------------------------------------------
// String accessors — generated by macro
// ---------------------------------------------------------------------------

macro_rules! str_set {
    ($fn:ident, $k:ident) => {
        /// Persist the string in instance storage and extend the TTL.
        pub fn $fn(env: &Env, v: &String) {
            bump(env);
            env.storage().instance().set(&DataKey::$k, v);
        }
    };
}
macro_rules! str_get {
    ($fn:ident, $k:ident) => {
        /// Read the string from instance storage.
        ///
        /// # Panics
        /// Panics with [`PhoenixLpError::NotInitialized`] if the key is absent.
        pub fn $fn(env: &Env) -> String {
            bump(env);
            env.storage()
                .instance()
                .get(&DataKey::$k)
                .unwrap_or_else(|| panic_with_error!(env, PhoenixLpError::NotInitialized))
        }
    };
}

addr_set!(set_vault, Vault);
addr_get!(get_vault, Vault);
addr_set!(set_asset_a, AssetA);
addr_get!(get_asset_a, AssetA);
addr_set!(set_asset_b, AssetB);
addr_get!(get_asset_b, AssetB);
addr_set!(set_share_token, ShareToken);
addr_get!(get_share_token, ShareToken);
addr_set!(set_phoenix_pool, PhoenixPool);
addr_get!(get_phoenix_pool, PhoenixPool);
addr_set!(set_manager, Manager);
addr_get!(get_manager, Manager);
str_set!(set_name, Name);
str_get!(get_name, Name);

// ---------------------------------------------------------------------------
// Pause flag
// ---------------------------------------------------------------------------

/// Persist the pause flag.
pub fn set_paused(env: &Env, v: bool) {
    bump(env);
    env.storage().instance().set(&DataKey::Paused, &v);
}

/// Read the pause flag (defaults to `false` when not yet set).
pub fn get_paused(env: &Env) -> bool {
    bump(env);
    env.storage()
        .instance()
        .get(&DataKey::Paused)
        .unwrap_or(false)
}

// ---------------------------------------------------------------------------
// Total shares
// ---------------------------------------------------------------------------

/// Persist the cumulative Phoenix share token balance.
pub fn set_total_shares(env: &Env, v: i128) {
    bump(env);
    env.storage().instance().set(&DataKey::TotalShares, &v);
}

/// Read the cumulative Phoenix share token balance (defaults to `0`).
pub fn get_total_shares(env: &Env) -> i128 {
    bump(env);
    env.storage()
        .instance()
        .get(&DataKey::TotalShares)
        .unwrap_or(0)
}
