//! PhoenixLpStrategy storage layout.
#![allow(dead_code)]
//!
//! All state is kept in **instance storage** so its TTL is tied to the contract
//! instance itself.
//!
//! | Key            | Type      | Description                                      |
//! |----------------|-----------|--------------------------------------------------|
//! | `Vault`        | `Address` | Owning vault contract                            |
//! | `AssetA`       | `Address` | First token in the Phoenix pair                  |
//! | `AssetB`       | `Address` | Second token in the Phoenix pair                 |
//! | `ShareToken`   | `Address` | Phoenix LP share token (auto-queried from pool)  |
//! | `PhoenixPool`  | `Address` | Phoenix pool contract                            |
//! | `Name`         | `String`  | Human-readable strategy name                     |
//! | `TotalShares`  | `i128`    | Running total of Phoenix share tokens held       |

use crate::error::PhoenixLpError;
use soroban_sdk::{contracttype, panic_with_error, Address, Env, String};

// ---------------------------------------------------------------------------
// TTL constants (ledgers; ~6 s/ledger on Stellar mainnet)
// ---------------------------------------------------------------------------

/// Ledgers added to the instance TTL on every entry-point call.
/// 34 560 ledgers ≈ 2.4 days.
pub const INSTANCE_BUMP_AMOUNT: u32 = 34_560;

/// Trigger a bump when the remaining instance TTL drops below this threshold.
/// 17 280 ledgers ≈ 1.2 days.
pub const INSTANCE_LIFETIME_THRESHOLD: u32 = 17_280;
/// Persistent init flag TTL: effectively permanent.
pub const PERSISTENT_BUMP_AMOUNT: u32 = u32::MAX;
pub const PERSISTENT_LIFETIME_THRESHOLD: u32 = u32::MAX / 2;

// ---------------------------------------------------------------------------
// Storage key enum
// ---------------------------------------------------------------------------

/// All keys stored in instance storage by the PhoenixLpStrategy.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum DataKey {
    /// Address of the vault that owns this strategy deployment.
    Vault,
    /// First token in the Phoenix liquidity pair (e.g. USDC).
    AssetA,
    /// Second token in the Phoenix liquidity pair (e.g. XLM).
    AssetB,
    /// Phoenix LP share token contract address.
    /// Automatically queried from the pool during `initialize` via
    /// `phoenix_pool.query_share_token_address()`.
    ShareToken,
    /// Phoenix pool contract used for `provide_liquidity` / `withdraw_liquidity`.
    PhoenixPool,
    /// Human-readable name for this strategy instance.
    Name,
    /// Cumulative Phoenix share tokens held by this strategy contract.
    /// Incremented on `deposit_liquidity`, decremented on `withdraw`.
    TotalShares,

    /// Factory address cached during initialize so get_total_value can reach
    /// AssetHandler without calling back into the vault (re-entry prevention).
    Factory,
    /// Persistent initialization flag.
    Initialized,
}

// ---------------------------------------------------------------------------
// Internal TTL helper
// ---------------------------------------------------------------------------

fn bump(env: &Env) {
    env.storage()
        .instance()
        .extend_ttl(INSTANCE_LIFETIME_THRESHOLD, INSTANCE_BUMP_AMOUNT);
}

// ---------------------------------------------------------------------------
// Initialization guard
// ---------------------------------------------------------------------------

/// Persist the initialization flag in persistent storage so instance TTL expiry
/// cannot reopen initialization for a strategy address that still holds shares.
pub fn set_initialized(env: &Env) {
    env.storage().persistent().set(&DataKey::Initialized, &true);
    env.storage().persistent().extend_ttl(
        &DataKey::Initialized,
        PERSISTENT_LIFETIME_THRESHOLD,
        PERSISTENT_BUMP_AMOUNT,
    );
}

/// Return `true` when the strategy has been initialized.
pub fn is_initialized(env: &Env) -> bool {
    env.storage().persistent().has(&DataKey::Initialized)
}

// ---------------------------------------------------------------------------
// Address accessors — generated by macro
// ---------------------------------------------------------------------------

macro_rules! addr_set {
    ($fn:ident, $k:ident) => {
        /// Persist the address in instance storage and extend the TTL.
        pub fn $fn(env: &Env, v: &Address) {
            bump(env);
            env.storage().instance().set(&DataKey::$k, v);
        }
    };
}
macro_rules! addr_get {
    ($fn:ident, $k:ident) => {
        /// Read the address from instance storage.
        ///
        /// # Panics
        /// Panics with [`PhoenixLpError::NotInitialized`] if the key is absent.
        pub fn $fn(env: &Env) -> Address {
            bump(env);
            env.storage()
                .instance()
                .get(&DataKey::$k)
                .unwrap_or_else(|| panic_with_error!(env, PhoenixLpError::NotInitialized))
        }
    };
}

// Factory address helpers
pub fn set_factory(env: &Env, v: &Address) {
    bump(env);
    env.storage().instance().set(&DataKey::Factory, v);
}

pub fn get_factory(env: &Env) -> Option<Address> {
    bump(env);
    env.storage().instance().get(&DataKey::Factory)
}

// ---------------------------------------------------------------------------
// String accessors — generated by macro
// ---------------------------------------------------------------------------

macro_rules! str_set {
    ($fn:ident, $k:ident) => {
        /// Persist the string in instance storage and extend the TTL.
        pub fn $fn(env: &Env, v: &String) {
            bump(env);
            env.storage().instance().set(&DataKey::$k, v);
        }
    };
}
macro_rules! str_get {
    ($fn:ident, $k:ident) => {
        /// Read the string from instance storage.
        ///
        /// # Panics
        /// Panics with [`PhoenixLpError::NotInitialized`] if the key is absent.
        pub fn $fn(env: &Env) -> String {
            bump(env);
            env.storage()
                .instance()
                .get(&DataKey::$k)
                .unwrap_or_else(|| panic_with_error!(env, PhoenixLpError::NotInitialized))
        }
    };
}

addr_set!(set_vault, Vault);
addr_get!(get_vault, Vault);
addr_set!(set_asset_a, AssetA);
addr_get!(get_asset_a, AssetA);
addr_set!(set_asset_b, AssetB);
addr_get!(get_asset_b, AssetB);
addr_set!(set_share_token, ShareToken);
addr_get!(get_share_token, ShareToken);
addr_set!(set_phoenix_pool, PhoenixPool);
addr_get!(get_phoenix_pool, PhoenixPool);
str_set!(set_name, Name);
str_get!(get_name, Name);

// ---------------------------------------------------------------------------
// Total shares
// ---------------------------------------------------------------------------

/// Persist the cumulative Phoenix share token balance.
pub fn set_total_shares(env: &Env, v: i128) {
    bump(env);
    env.storage().instance().set(&DataKey::TotalShares, &v);
}

/// Read the cumulative Phoenix share token balance (defaults to `0`).
pub fn get_total_shares(env: &Env) -> i128 {
    bump(env);
    env.storage()
        .instance()
        .get(&DataKey::TotalShares)
        .unwrap_or(0)
}
